### ISSUE TITLE
Cambiar de modelo

### ISSUE THREAD

**Issue by KrisFortnite** [Omega-Slender/INTENSE-RP-API#1]
Una pregunta buen omega, si quisiera cambiar de bot y usar otro como por ejemplo uno personalizado o simplemente GPT-4 ¿Que parte del codigo deberia cambiar para lograr ese ajuste?

**Comment by Omega-Slender** [comment]
No tienes que cambiar nada, simplemente inicias el proyecto. Luego, desde la página de POE seleccionas el bot de tu preferencia.
