### ISSUE TITLE
Roleplay Largo

### ISSUE THREAD

**Issue by KrisFortnite** [Omega-Slender/INTENSE-RP-API#2]
Señor Omega, seria tan amable de explicarme como hacer para continuar un RP ya bastante avanzado? Lo que hacia SillyTavern era que divdía el contexto de la conversación por lotes para no enviar un texto extra largo ya que eso confunde al bot y hace que no responda. Lo que hacia SillyTavern es basicamente al dividir el mensaje en varios ponia al final de cada uno un " Reply with a full stop only" para que el bot responda simplemente con un " . " y asi optimizar la conversación y que pueda entender todo el contexto posible.

Basicamente lo que le pido (Si es que puede y lo considera) es que dependiendo de la cantidad de mensajes se dividia por lotes para poder seguir una conversación larga

**Comment by Omega-Slender** [comment]
En la última actualización ya he agregado un sistema que separa el contenido en 2 mensajes.

**Comment by KrisFortnite** [comment]
Q grande, esto es inicialmente bueno para conversaciones normales. Sin embargo, para una conversación en la que por ejemplo hay 50 mensajes o más sigue sin funcionar ¿Porque pasa esto? pues esto se debe a que se manda toda la conversación entera en un solo mensaje, cosa que como es de esperar obviamente va a dar error. 

Por eso es importante que, dependiendo de la cantidad de texto, se divida automáticamente en varios mensajes. Si has conseguido obtener la conversación y mandarla a Poe ¿Porque no implementas unas lineas en las que a partir de cierto numero de caracteres se divida automaticamente en varios mensajes? 

Yo sé que tendrias que por ejemplo implementar independientemente de esas lineas de codigo cambiar la actual que se encarga de leer los mensajes de respuesta pero no seria tan dificil. Tu ponle que cuando se divida en varios mensajes se modifique el contenido de cada mensaje y se le añada al final \[Reply to this message with a full stop only\]. 

El bot en el 90% de las ocasiones respondera simplemente diciendo " . " entonces pues solo tendrias que añadir un "if" dentro de ese codigo que se encargue de analizar si el mensaje de respuesta del bot es simplemente un " . " y si es afirmativo tan solo dile que ese mensaje se ignore y se sigan mandando los demás mensajes que quedan hasta que, como el mensaje final no tiene el la instruccion de responder con un punto, si se lea el mensaje y se envie como respuesta dentro de SillyTavern.

De nuevo, muchas gracias por tu tiempo y dedicación señor Omega.
